version: '3.8'

services:
  idr-frontend:
    container_name: idr-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ENV_FILE=.env
    restart: unless-stopped
